version: '3.8'

services:
  minotaur:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OSV_API_BASE_URL=https://api.osv.dev
      - MAX_DEPENDENCIES=1000
      - REPO_CLONE_TIMEOUT=300
      - TRIAGE_CONFIDENCE_THRESHOLD=0.7
      - LOG_LEVEL=INFO
    volumes:
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
